# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


trigger:
- master

jobs:
- job: NPM
  pool:
    name: Host linux local
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Build Artifact'
    inputs:
      PathtoPublish: build
      ArtifactName: 'build_$(Build.BuildId)'

- job: Docker
  dependsOn: NPM
  pool:
    name: Host linux local
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifact'
    inputs:
      artifactName: 'build_$(Build.BuildId)'
      downloadPath: '$(System.DefaultWorkingDirectory)/build'

  - task: Docker@0
    displayName: Build
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryConnection: 'DRTD Registry'
      action: 'Run a Docker command'
      customCommand: 'build -t drtd-web:$(Build.BuildId) -f ./Dockerfile.nginx .'

  - task: Docker@0
    displayName: Tag
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryConnection: 'DRTD Registry'
      action: 'Run a Docker command'
      customCommand: 'tag drtd-web:$(Build.BuildId) drtd.azurecr.io/drtd-web:$(Build.BuildId)'

  - task: Docker@0
    displayName: Push
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryConnection: 'DRTD Registry'
      action: 'Run a Docker command'
      customCommand: 'push drtd.azurecr.io/drtd-web:$(Build.BuildId)'
      
  - task: CopyFiles@2
    displayName: 'Copy kubernetes manifests files'
    inputs:
      SourceFolder: ci
      Contents: '*.yaml'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact in drop folder'